### ISSUE TITLE
missing author info

### ISSUE THREAD

**Issue by JayBeRayBearGun** [kitian616/gitalk-demo#66]
Next to the author icon there is no name apearing and the author show profile shows up empty. 

Where should I look to fix it?

**Comment by kitian616** [comment]
did you do as [this](https://tianqi.name/jekyll-TeXt-theme/docs/en/authors) said?

**Comment by JayBeRayBearGun** [comment]
Hi! thanks for the response. I fixed it, turned out to be a naming mistake :( Sorry to have wasted your time.
